---
abstract: 'Read aarddict dictionaries'
author:
  - 'Marius Gavrilescu <marius@ieval.ro>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Aard
no_index:
  directory:
    - t
    - inc
requires:
  IO::Uncompress::Bunzip2: '0'
  IO::Uncompress::Inflate: '0'
  JSON::MaybeXS: '0'
  List::Util: '0'
  UUID::Tiny: '0'
  perl: '5.014000'
resources:
  repository: https://git.ieval.ro/?p=aard.git
version: '0.001'
